/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNodeDialog: typeof import('./src/components/AddNodeDialog.vue')['default']
    AdvancedChart: typeof import('./src/components/AdvancedChart.vue')['default']
    AnimatedNumber: typeof import('./src/components/ui/AnimatedNumber.vue')['default']
    CommandDialog: typeof import('./src/components/CommandDialog.vue')['default']
    ConfigEditor: typeof import('./src/components/ConfigEditor.vue')['default']
    ConfigHistoryDialog: typeof import('./src/components/ConfigHistoryDialog.vue')['default']
    ConfigViewDialog: typeof import('./src/components/ConfigViewDialog.vue')['default']
    DockerManager: typeof import('./src/components/DockerManager.vue')['default']
    EcNode: typeof import('./src/components/EcNode.vue')['default']
    EditNodeDialog: typeof import('./src/components/EditNodeDialog.vue')['default']
    ErrorDetailsDialog: typeof import('./src/components/ErrorDetailsDialog.vue')['default']
    ErrorTimeline: typeof import('./src/components/ErrorTimeline.vue')['default']
    EventLog: typeof import('./src/components/EventLog.vue')['default']
    GlassCard: typeof import('./src/components/ui/GlassCard.vue')['default']
    GradientCard: typeof import('./src/components/ui/GradientCard.vue')['default']
    HelpTooltip: typeof import('./src/components/HelpTooltip.vue')['default']
    ManualPumpControl: typeof import('./src/components/node-config/ManualPumpControl.vue')['default']
    NodeCard: typeof import('./src/components/NodeCard.vue')['default']
    NodeDiscoveryIndicator: typeof import('./src/components/NodeDiscoveryIndicator.vue')['default']
    NodeHealthIndicator: typeof import('./src/components/NodeHealthIndicator.vue')['default']
    NodeManagementCard: typeof import('./src/components/NodeManagementCard.vue')['default']
    NodeMemoryCard: typeof import('./src/components/NodeMemoryCard.vue')['default']
    NodeMetadataCard: typeof import('./src/components/NodeMetadataCard.vue')['default']
    NodeStatusIndicator: typeof import('./src/components/ui/NodeStatusIndicator.vue')['default']
    PhDetail: typeof import('./src/components/detail/PhDetail.vue')['default']
    PhNode: typeof import('./src/components/PhNode.vue')['default']
    PullToRefreshIndicator: typeof import('./src/components/ui/PullToRefreshIndicator.vue')['default']
    PumpCalibrationDialog: typeof import('./src/components/node-config/PumpCalibrationDialog.vue')['default']
    QuickAddNode: typeof import('./src/components/QuickAddNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleManager: typeof import('./src/components/ScheduleManager.vue')['default']
    Sparkline: typeof import('./src/components/ui/Sparkline.vue')['default']
    StatCard: typeof import('./src/components/ui/StatCard.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    SystemStatusCard: typeof import('./src/components/SystemStatusCard.vue')['default']
    TelegramSetupGuide: typeof import('./src/components/TelegramSetupGuide.vue')['default']
    TelemetryChart: typeof import('./src/components/TelemetryChart.vue')['default']
    UniversalDialog: typeof import('./src/components/ui/UniversalDialog.vue')['default']
  }
}
