# ========================================
# MESH HYDRO V2 - DOCKER COMPOSE
# ========================================
# 
# ⚠️ ВАЖНО: Только СЕРВЕРНЫЕ компоненты!
#
# В Docker:
#   - Mosquitto MQTT Broker
#   - PostgreSQL Database (реляционная БД)
#   - Laravel Backend API
#   - MQTT Listener (PHP)
#   - Vue.js Frontend
#
# НЕ в Docker (физическое железо):
#   - ROOT Node (ESP32-S3) - прошивается через idf.py
#   - NODE Climate (ESP32) - прошивается через idf.py
#   - NODE pH/EC (ESP32-S3) - прошивается через idf.py
#   - и другие узлы...
#
# 📡 Подключение ESP32:
#   - ESP32 подключается к MQTT брокеру по IP хоста и порту 1883
#   - Внутри Docker сервисы общаются по именам (mosquitto, backend, postgres)
#   - Порт 1883 проброшен на хост для доступа ESP32
# ========================================

services:
  # ========================================
  # PostgreSQL Database
  # Профессиональная СУБД с JSONB поддержкой
  # ========================================
  postgres:
    image: postgres:15.4-alpine
    container_name: hydro_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hydro_system
      POSTGRES_USER: hydro
      POSTGRES_PASSWORD: hydro_secure_pass_2025
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"  # Для доступа с хоста (опционально)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hydro_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hydro -d hydro_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================================
  # MQTT Broker (Mosquitto)
  # Для приема данных от ESP32 узлов
  # ========================================
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: hydro_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"     # MQTT
      - "9001:9001"     # WebSocket (опционально)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - hydro_network

  # ========================================
  # Backend (Laravel 10)
  # REST API + MQTT обработка
  # PostgreSQL база данных
  # ========================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hydro_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "6001:6001"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_LEVEL=debug
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=hydro_system
      - DB_USERNAME=hydro
      - DB_PASSWORD=hydro_secure_pass_2025
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - BROADCAST_DRIVER=reverb
      - REVERB_APP_ID=hydro-app
      - REVERB_APP_KEY=hydro-app-key
      - REVERB_APP_SECRET=hydro-app-secret
      - REVERB_HOST=reverb
      - REVERB_PORT=8080
      - REVERB_SCHEME=http
      - REVERB_SERVER_HOST=0.0.0.0
      - REVERB_SERVER_PORT=8080
    volumes:
      # Монтирование локального кода (только для разработки)
      # - ./backend:/var/www/html
      - backend_storage:/var/www/html/storage
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
    networks:
      - hydro_network
    command: >
      sh -c "php artisan migrate --force &&
             php artisan reverb:start --host=0.0.0.0 --port=6001 &
             php artisan serve --host=0.0.0.0 --port=8000"

  # ========================================
  # MQTT Listener (Laravel Artisan)
  # Принимает данные от ESP32 через MQTT
  # ========================================
  mqtt_listener:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hydro_mqtt_listener
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_LEVEL=debug
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=hydro_system
      - DB_USERNAME=hydro
      - DB_PASSWORD=hydro_secure_pass_2025
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - BROADCAST_DRIVER=reverb
      - REVERB_APP_ID=hydro-app
      - REVERB_APP_KEY=hydro-app-key
      - REVERB_APP_SECRET=hydro-app-secret
      - REVERB_HOST=reverb
      - REVERB_PORT=8080
      - REVERB_SCHEME=http
      - REVERB_SERVER_HOST=0.0.0.0
      - REVERB_SERVER_PORT=8080
    # volumes:
      # Монтирование локального кода (только для разработки)
      # - ./backend:/var/www/html
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - hydro_network
    command: php artisan mqtt:listen

  # ========================================
  # Scheduler (Laravel Artisan)
  # Автоматическое выполнение scheduled tasks
  # ========================================
  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hydro_scheduler
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_LEVEL=debug
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=hydro_system
      - DB_USERNAME=hydro
      - DB_PASSWORD=hydro_secure_pass_2025
      - BROADCAST_DRIVER=reverb
      - REVERB_APP_ID=hydro-app
      - REVERB_APP_KEY=hydro-app-key
      - REVERB_APP_SECRET=hydro-app-secret
      - REVERB_HOST=reverb
      - REVERB_PORT=8080
      - REVERB_SCHEME=http
    depends_on:
      postgres:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - hydro_network
    command: php artisan schedule:work

  # ========================================
  # Frontend (Vue.js 3)
  # Веб-интерфейс для мониторинга ESP32
  # ========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
        - VITE_WS_HOST=localhost
        - VITE_WS_PORT=8080
        - VITE_PUSHER_KEY=hydro-app-key
    container_name: hydro_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - hydro_network

  # ========================================
  # Laravel Reverb WebSocket Server
  # Встроенный WebSocket сервер Laravel 11
  # ========================================
  reverb:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hydro_reverb
    restart: unless-stopped
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_LEVEL=debug
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=hydro_system
      - DB_USERNAME=hydro
      - DB_PASSWORD=hydro_secure_pass_2025
      - BROADCAST_DRIVER=reverb
      - REVERB_APP_ID=hydro-app
      - REVERB_APP_KEY=hydro-app-key
      - REVERB_APP_SECRET=hydro-app-secret
      - REVERB_HOST=reverb
      - REVERB_PORT=8080
      - REVERB_SCHEME=http
      - REVERB_SERVER_HOST=0.0.0.0
      - REVERB_SERVER_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hydro_network
    volumes:
      - backend_storage:/var/www/html/storage

  # ========================================
  # Nginx (Reverse Proxy) - опционально
  # ========================================
  nginx:
    image: nginx:1.27-alpine
    container_name: hydro_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
      - frontend
    networks:
      - hydro_network
    profiles:
      - production  # Запускается только с --profile production

# ========================================
# Networks
# ========================================
networks:
  hydro_network:
    driver: bridge

# ========================================
# Volumes (постоянное хранение данных)
# ========================================
volumes:
  postgres_data:
    driver: local
  backend_storage:
    driver: local

